### ISSUE TITLE
error on import

### ISSUE THREAD

**Issue by seyhbold** [xudafeng/autoresponsive-react#16]
Hi,

I would like to use this component but when I import AutoResponsive with:

```javascript
import AutoResponsive from 'autoresponsive-react';
```

I get:

```
ERROR in ./~/autoresponsive-react/lib/index.js
Module parse failed: C:\Devel\dgg\prds\node_modules\autoresponsive-react\lib\index.js Line 17: Unexpected token {
You may need an appropriate loader to handle this file type.
| let Common = require('autoresponsive-common');
|
| let {
|   Util,
|   GridSort
 @ ./~/autoresponsive-react/index.js 16:17-33
```

Do you have a hint what I am doing wrong?

Thanks
Ludwig

**Comment by xudafeng** [comment]
Here is an example, hope to help you. [autoresponsive_react_native_sample](https://github.com/xudafeng/autoresponsive_react_native_sample) @seyhbold

**Comment by tony99nyr** [comment]
@xudafeng the example you provided doesn't help me resolve this issue.  I am running into it as well trying to import the library as an es6 module.  @seyhbold did you figure this problem out?

```javascript
import React from 'react';
import AutoResponsive from 'autoresponsive-react';
```

**Comment by tony99nyr** [comment]
@xudafeng Can you provide a babel compiled version of autoresponsive-common and autoresponsive-react maybe in a /dist folder instead of lib?

**Comment by tsusini** [comment]
+1

**Comment by xudafeng** [comment]
https://github.com/xudafeng/autoresponsive-react/releases/edit/1.1.7
