### ISSUE TITLE
overflow: hidden on grid items may be too restrictive

### ISSUE THREAD

**Issue by rayshan** [xudafeng/autoresponsive-react#30]
Hello, currently `overflow: hidden` is set on all the grid items. This doesn't allow certain styling on the grid items, such as CSS scaling on `:hover`. An example of such usage can be seen on https://shan.io/photography/. Scroll down and hover on the photos with mouse.

**Comment by xudafeng** [comment]
@rayshan It sounds great, could you give a `pull request` with your code implementation? :smile:

**Comment by xudafeng** [comment]
Fixed.
