### ISSUE TITLE
How to make height fit the content?

### ISSUE THREAD

**Issue by mixdesign** [xudafeng/autoresponsive-react#33]
I want fixed width, but dynamic height which should resize depending on html content. Is it possible? Thatnk you!

**Comment by xudafeng** [comment]
@mixdesign It could not support dynamic height adaptation in real-time rendering, but offline rendering can be used to get the height at the time when you want.

**Comment by mixdesign** [comment]
What you mean saying offline? I call an API, get the data of array, create each card with different height content. That's all.

**Comment by xudafeng** [comment]
Do `pre rendering` with data in an other container before append it.
