### ISSUE TITLE
Initial animation disable option?

### ISSUE THREAD

**Issue by kschethan** [xudafeng/autoresponsive-react#37]
Hey, this is a great library. Thanks for this.
I have a question, is there an option to disable the initial animation, may be we can pass it via getAutoResponsiveProps() ?

**Comment by xudafeng** [comment]
http://xudafeng.github.io/autoresponsive-react/#closeanimation

**Comment by xudafeng** [comment]
@kschethan [closeanimation](http://xudafeng.github.io/autoresponsive-react/#closeanimation)

**Comment by kschethan** [comment]
Thanks for replying. 
But that removes all the animations, even the one when you resize the window. I want to disable only the initial animation. Is there any way?

**Comment by xudafeng** [comment]
@kschethan I know what you wanna. How about hack with `css !important` to disable animation？Recover it with browser scripts at any time.
