### ISSUE TITLE
Suggestions for centering the resulting container?

### ISSUE THREAD

**Issue by adcooley** [xudafeng/autoresponsive-react#38]
It appears that after the container is rendered, the container width > the width of all the items. I tried calculating the # of columns that would be rendered myself and adding padding to adjust, but it's not quite right.

Anyone have a suggestion for this?

**Comment by xudafeng** [comment]
what are you want to do? @adcooley

**Comment by samkit** [comment]
I agree. Its an important feature to have. For example: I have grid cells of width 200 and screen width is 500. If I set cellMargin as 20 and margin on individual cells as 20 then I am still left with 60 pixels on the right compared to 20 pixels on the left.

<img width="292" alt="screen shot 2016-11-24 at 9 44 57 am" src="https://cloud.githubusercontent.com/assets/1732809/20586527/b899cd52-b22a-11e6-8aad-0d7d266a1435.png">

**Comment by MahmoudAlyuDeen** [comment]
Any elegant solution to this yet?

**Comment by xiaweiss** [comment]
如果是量列，React native可以这样设置
itemMargin={(screenWidth - 160 * 2) / 3}

子元素样式
width: 160,
transform: [{translateX: (screenWidth - 160 * 2) / 3}],
